"""empty message

Revision ID: 1abeb941d4e5
Revises: e6070f807ba2
Create Date: 2019-06-21 12:09:46.391850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1abeb941d4e5'
down_revision = 'e6070f807ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schema', sa.String(), nullable=True),
    sa.Column('connection_string', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schema')
    )
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('connections')
    # ### end Alembic commands ###
