"""empty message

Revision ID: 1e14f9fddd1f
Revises: 
Create Date: 2019-06-12 11:36:01.147992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e14f9fddd1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schema', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('sql_alchemy_definition', sa.String(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schema')
    )
    op.create_index(op.f('ix_countries_country_name'), 'countries', ['country_name'], unique=True)
    op.create_index(op.f('ix_countries_iso_code'), 'countries', ['iso_code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_countries_iso_code'), table_name='countries')
    op.drop_index(op.f('ix_countries_country_name'), table_name='countries')
    op.drop_table('tables')
    # ### end Alembic commands ###
