"""empty message

Revision ID: 45587a9fecb2
Revises: 1abeb941d4e5
Create Date: 2019-06-25 08:15:16.322757

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45587a9fecb2'
down_revision = '1abeb941d4e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('country_name', sa.TEXT(length=255), nullable=True),
    sa.Column('iso_code', sa.TEXT(length=255), nullable=True),
    sa.Column('currency_code', sa.TEXT(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('item_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('item_description', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('regions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('country_name', sa.TEXT(), nullable=True),
    sa.Column('iso_code', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_md5', sa.String(), nullable=True),
    sa.Column('salt', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tables', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('users')
    op.drop_table('regions')
    op.drop_table('items')
    op.drop_table('countries')
    # ### end Alembic commands ###
