"""empty message

Revision ID: e6070f807ba2
Revises: 1e14f9fddd1f
Create Date: 2019-06-19 11:55:49.392350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6070f807ba2'
down_revision = '1e14f9fddd1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tables', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tables', type_='unique')
    # ### end Alembic commands ###
